#!/usr/bin/env bash
# scp $file_path $user_naame@$ip:$dir_path $ssh_path

if [ "$#" -lt 3 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 0
fi

file_path="$1"
ip_address="$2"
user_name="$3"
ssh_path="$4"
if [ "$#" -lt 4 ]
then
    scp  -o StrictHostKeyChecking=no "$file_path" "$user_name@$ip_address":~/
else
    scp  -o StrictHostKeyChecking=no "$file_path" "$user_name@$ip_address":~/ -i "$ssh_path"
fi
