#!/usr/bin/env bash
# script to install nginx on remote server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart

exit 0
