#!/usr/bin/env bash
# to make a redirection url

sudo apt-get update
sudo apt-get install nginx

base_dir="/etc/nginx"
avail="/sites-available"
enab="/sites-enabled"
base_var="/var/www/techiocean.tech"
file="/techiocean.tech"


if [ ! -d "$base_var" ]; then
    sudo mkdir -p "$base_var"
fi
echo "Hello World!" | sudo tee "$base_var"/index.html > /dev/null

sudo rm "$base_dir$avail$file"
sudo unlink "$base_dir$enab$file"

sudo touch "$base_dir$avail$file"

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root "$base_var";
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee "$base_dir$avail$file" > /dev/null
sudo ln -s "$base_dir$avail$file" "$base_dir$enab"

sudo nginx -t
sudo service nginx restart
