#!/usr/bin/env bash
# Install the load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver web-01 54.174.3.157 check\n\tserver web-02 54.242.203.162 check\n" >> /etc/haproxy/haproxy.cfg'
# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy start
