#!/usr/bin/env bash
# fil to add custom header to nginx
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt update
sudo apt-get install haproxy=2.6.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
echo "frontend techi-frontend
    bind *:80
    mode http
    default_backend techi-backend
backend techi-backend
    balance roundrobin
    server web-01 54.174.3.157:80 check
    server web-02 54.242.203.162:80 check" | sudo tee -a "/etc/haproxy/haproxy.cfg"
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
