#!/usr/bin/env bash
# Find the PID of the 4-to_infinity_and_beyond process
# shellcheck disable=SC2009
pid=$(ps aux | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')
if [ -z "$pid" ]; then
    echo "4-to_infinity_and_beyond process is not running."
else
    # Use the kill command to terminate the process with SIGTERM (15)
    kill "$pid"
    echo "4-to_infinity_and_beyond process with PID $pid has been terminated."
fi
