#!/usr/bin/env bash
#script to change localhost and facebook mapping

if [ "$EUID" -ne 0 ]; then
	echo "must be with root privilage"
	exit 1
fi

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts